app/apps/dashboard/urls.py
from django.urls import path
from apps.dashboard.views import *

app_name = 'dashboard'

urlpatterns = [
    # home
    path('dashboard/', DashboardView.as_view(), name='home'),
]

app/apps/geografico/urls.py
from django.urls import path

from apps.geografico.views.paises.views import *
from apps.geografico.views.provincias.views import *
from apps.geografico.views.localidades.views import *

app_name = 'geografico'

urlpatterns = [
    #PAISES
    path('paises/list/', PaisesListView.as_view(), name='paises_list'),
    path('paises/add/', PaisesCreateView.as_view(), name='paises_create'),
    path('paises/update/<int:pk>/', PaisesUpdateView.as_view(), name='paises_update'),
    path('paises/delete/<int:pk>/', PaisesDeleteView.as_view(), name='paises_delete'),
    #Provincias
    path('provincias/list/', ProvinciasListView.as_view(), name='provincias_list'),
    path('provincias/add/', ProvinciasCreateView.as_view(), name='provincias_create'),
    path('provincias/update/<int:pk>/', ProvinciasUpdateView.as_view(), name='provincias_update'),
    path('provincias/delete/<int:pk>/', ProvinciasDeleteView.as_view(), name='provincias_delete'),
    #Localidades
    path('localidades/list/', LocalidadesListView.as_view(), name='localidades_list'),
    path('localidades/add/', LocalidadesCreateView.as_view(), name='localidades_create'),
    path('localidades/update/<int:pk>/', LocalidadesUpdateView.as_view(), name='localidades_update'),
    path('localidades/delete/<int:pk>/', LocalidadesDeleteView.as_view(), name='localidades_delete'),
    
]

app/apps/parametros/urls.py
from django.urls import path

from apps.parametros.views.tipos_documentos.views import *
from apps.parametros.views.sexos.views import *
from apps.parametros.views.tarjetas.views import *
from apps.parametros.views.estados.views import *

app_name = 'parametros'

urlpatterns = [
    #Tipo de Documento
    path('tipos_documentos/list/', TiposDocumentosListView.as_view(), name='tipos_documentos_list'),
    path('tipos_documentos/add/', TiposDocumentosCreateView.as_view(), name='tipos_documentos_create'),
    path('tipos_documentos/update/<int:pk>/', TiposDocumentosUpdateView.as_view(), name='tipos_documentos_update'),
    path('tipos_documentos/delete/<int:pk>/', TiposDocumentosDeleteView.as_view(), name='tipos_documentos_delete'),
    #Sexos
    path('sexos/list/', SexosListView.as_view(), name='sexos_list'),
    path('sexos/add/', SexosCreateView.as_view(), name='sexos_create'),
    path('sexos/update/<int:pk>/', SexosUpdateView.as_view(), name='sexos_update'),
    path('sexos/delete/<int:pk>/', SexosDeleteView.as_view(), name='sexos_delete'),
    #Tarjetas
    path('tarjetas/list/', TarjetasListView.as_view(), name='tarjetas_list'),
    path('tarjetas/add/', TarjetasCreateView.as_view(), name='tarjetas_create'),
    path('tarjetas/update/<int:pk>/', TarjetasUpdateView.as_view(), name='tarjetas_update'),
    path('tarjetas/delete/<int:pk>/', TarjetasDeleteView.as_view(), name='tarjetas_delete'),
    # Estados
    path('estados/list/', EstadosListView.as_view(), name='estados_list'),
    path('estados/add/', EstadosCreateView.as_view(), name='estados_create'),
    path('estados/update/<int:pk>/', EstadosUpdateView.as_view(), name='estados_update'),
    path('estados/delete/<int:pk>/', EstadosDeleteView.as_view(), name='estados_delete'),
]

app/apps/usuarios/urls.py
from django.urls import path

from apps.usuarios.views.tipos_usuarios.views import *
from apps.usuarios.views.usuarios.views import *


app_name = 'usuarios'

urlpatterns = [
    #Usuarios
    path('usuarios/list/', UsuariosListView.as_view(), name='usuarios_list'),
    path('usuarios/add/', UsuariosCreateView.as_view(), name='usuarios_create'),
    path('usuarios/update/<int:pk>/', UsuariosUpdateView.as_view(), name='usuarios_update'),
    path('usuarios/delete/<int:pk>/', UsuariosDeleteView.as_view(), name='usuarios_delete'),
    # Tipos de Usuarios
    path('tipo_usuario/list/', TiposUsuariosListView.as_view(), name='tipo_usuario_list'),
    path('tipo_usuario/add/', TiposUsuariosCreateView.as_view(), name='tipo_usuario_create'),
    path('tipo_usuario/update/<int:pk>/', TiposUsuariosUpdateView.as_view(), name='tipo_usuario_update'),
    path('tipo_usuario/delete/<int:pk>/', TiposUsuariosDeleteView.as_view(), name='tipo_usuario_delete'),

]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
#from apps.login.views import LoginFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('geografico/', include('apps.geografico.urls')),
    path('parametros/', include('apps.parametros.urls')),
    path('', include('apps.login.urls')),
    path('', include('apps.dashboard.urls')),
    path('', include('apps.usuarios.urls')),
]

app/apps/dashboard/models.py
from django.db import models

# Create your models here.

app/apps/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    #@method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administración'
        return context

app/templates/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}

    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}

        <!-- Content -->
        <div class="content-wrapper">
             <!-- Fondo de Pantalla
             style="background-image: url('/static/img/fondo_template.jpg'); background-size: cover;"> -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right font-weight-bold">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
     <!-- /.control-sidebar -->
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    <script>
        //Controlar Sidebar, menu abierto
        var link_sidebar = $("a[href='{{request.path}}']");
        // Activamos el elemento.
        link_sidebar[0].classList = 'nav-link active';
        // Hacemos un recorrido recursivo de "abajo hacia arriba" del sidebar para ir abriendo menúes
        var els = [];
        var prof = 0;    //Controla la profundidad. Si hay muchos menúes anidados se debe aumentar.

        while (link_sidebar[0] && prof < 7) {
                if(link_sidebar[0].classList.value.includes('nav-item')){
                    link_sidebar[0].classList.value = 'nav-item menu-is-opening menu-open';
                }
                els.unshift(link_sidebar[0]);
                link_sidebar[0] = link_sidebar[0].parentNode;
                prof++;
            }
    </script>

    </body>
{% endblock %}

app/templates/dashboard.html
{% extends 'body.html' %}

<!-- imagen de fondo

<div class="content-wrapper"
     style="background-image: url('/static/img/fondo_template.jpg'); background-size: cover;">
</div>

-->

app/templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div class="alert alert-danger alert-dismissible">
                    Eliminar el Registro {{ object.nombre }}
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Eliminar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            submit_with_ajax(window.location.pathname, 'Notificación!', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- Fondo de Pantalla
        style="background-image: url('/static/img/fondo-template (footer).jpg'); background-size: cover;"> -->
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        <!-- Anything you want -->
    </div>
    <!-- Default to the left -->
    <strong> Copyright &copy 2021 CONASIS</a></strong><br>
    Todos los derechos reservados.
</footer>

app/templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al intentar guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field| add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}


        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            console.log(parameters);
            //var parameters = new FormData(this);
            console.log(parameters);
            submit_with_ajax(window.location.pathname, 'Confirmación', '¿Estás seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });

    </script>
{% endblock %}

app/templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block font-weight-bold">
            <a href="{% url 'dashboard:home' %}" class="nav-link">Inicio </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown font-weight-bold">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header"> Último inicio de sesión: {{ request.user.last_login }} </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm"><!-- algo --></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar contraseña
                    <span class="float-right text-muted text-sm"><!-- algo --></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <!-- Aca podria ir algo interesante -->
                    <p>Este sistema te permitirá realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Sistema de Control de Asistencia</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.5/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.5/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.5/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.5/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- AdminLTE -->
    <script src="{% static 'lib/adminlte-3.0.5/js/adminlte.min.js' %}"></script>
    <!-- SweetAlert2 -->
    <script src="{% static 'lib/sweetalert2-10.0.2/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm 3.3.4 -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>

{% block body %}

{% endblock %}
</html>

app/templates/index.html
{% extends 'body.html' %}

{% block content %}

{% endblock %}

app/templates/list.html
{% extends 'body.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}
                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false,
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {

                });
            });
        });
    </script>
{% endblock %}

app/templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{% url 'dashboard:home' %}" class="brand-link">
        <img src="{% static 'img/clock-white.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-normal">Control de Asistencia</span>
    </a>
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">



                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            Configuración
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <!-- USUARIOS -->
                    <ul class="nav nav-treeview">
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fas fa-users nav-icon"></i>
                                <p>
                                    Usuarios
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'usuarios:tipo_usuario_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Tipos de Usuarios</p>
                                    </a>
                                </li>
                                <!--<li class="nav-item">
                                    <a  class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Personas</p>
                                    </a>
                                </li>-->
                                <li class="nav-item">
                                     <a href="{% url 'usuarios:usuarios_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                                <!--<li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Roles</p>
                                    </a>
                                </li>-->
                            </ul>
                        </li>
                    </ul>

                    <!-- GEOGRAFICO -->

                    <ul class="nav nav-treeview">
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fas fa-globe-americas nav-icon"></i>
                                <p>
                                    Geográfico
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'geografico:paises_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Paises</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'geografico:provincias_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Provincias</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'geografico:localidades_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Localidades</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                    <!-- PARAMETROS -->

                    <ul class="nav nav-treeview">
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="fas fa-cog nav-icon"></i>
                                <p>
                                    Parametros
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'parametros:tipos_documentos_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Tipos de documentos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'parametros:sexos_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Sexos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                   <a href="{% url 'parametros:estados_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Estados</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'parametros:tarjetas_list' %}" class="nav-link">
                                        <i class="far fa-dot-circle nav-icon"></i>
                                        <p>Tarjetas</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
    </div>
</aside>

app/templates/view.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-search"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <!--
                <div class="alert alert-danger alert-dismissible">
                    Eliminar el Registro {{ object.nombre }}
                </div>
                -->

            </div>
            <div class="card-footer">
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-backspace"></i> Volver
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            submit_with_ajax(window.location.pathname, 'Notificación!', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}